### ISSUE TITLE
广播地址有误差

### ISSUE THREAD

**Issue by CN-CaoJun** [jokerC8/doip#1]
Hi 朋友
           我们在学习您的大作的时候发现有个小问题，doip_entity.c，line843 广播地址填写不准确，导致车辆公告不能发送，能否确认下是不是bug。

**Comment by CN-CaoJun** [comment]
确切来说是发送了之后收不到

**Comment by jokerC8** [comment]
嗯，是有问题，这段时间会抽空完善下，现在很多功能都没弄

**Comment by CN-CaoJun** [comment]
great！
